apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  template:
    metadata: 
      labels: 
        app: second-app
    spec: 
      containers: 
        - name: seocnd-node
          image: nilmr45/kub-first-app:2