apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 8000      # outside facing port
      targetPort: 8000     # insdie of container where the request is forwarded