apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: nilmr45/kub-demo-user:latest
          env:
            - name: AUTH_ADDRESS
              # value: "10.105.151.92" # inside a pod we can use localhost to communicate with conatiners
              value: "auth-service"
